### ISSUE TITLE
Simplify `Evaluator` interface

### ISSUE THREAD

**Issue by jack-fs** [gradientinstitute/causal-inspection#19]
- Rationalise `evaluate_test`, `evaluate_train` etc.
- Modify `aggregate` function to take lists of Evaluation artefacts, aggregate them to a single artefact

**Comment by jack-fs** [comment]
If `Evaluator.evaluate` is a side-effect-free function:
  (model, data) -> Evaluation artefact
then we can't reasonably preserve the interface of `model_evaluation.bootstrap_model` or `model_evaluation.crossval_model`; both return `Evaluator` objects which implicitly contain the evaluation information (actually they are assumed to mutate the `Evaluator` objects they are given). 

There are a number of ways to go ahead:
- make `Evaluator` objects mutate their state when `evaluate()` is used (with an agreed-upon semantics, e.g. does the object *over-write* or *append* to its state if evaluate() is called twice?)
  - This brings up problems of thread safety
- make it explicit when an `Evaluator` mutates state; e.g. create a `ev.copy_with_evaluation(evaluation)` method; this would allow e.g. bootstrapping code to run all the evaluators, collect their results, aggregate them, and then set the evaluation before returning, e.g.
```
ev = DummyEvaluator()
...
ev.prepare(data)
evaluations = [ev.evaluate(data_folds[i]) for i in range(len(data_folds))]
agg_evaluation = ev.aggregate(evaluations)
agg_evaluator = ev.copy_with_evaluation(agg_evaluation)
return agg_evaluator
```
- Leave the `Evaluator`s' state fixed once  prepare() is called, and have bootstrap return a list of tuples `(evaluator, result)`. This is the current approach, and is the one I prefer, but does break with the sklearn convention

**Comment by dsteinberg** [comment]
I like the last approach too - could design an evaluator as an elaborate closure?
the `__init__` and `prepare` methods set up the state of the evaluator, then the `evaluate` method is the closed-over method and does not change the state of the object, all it does is return results.

Perhaps `prepare` could return an evaluate function that guarantees an immutable state?

**Comment by jack-fs** [comment]
4c9a15b mostly addresses this;
