### ISSUE TITLE
Transition away from Flake8 for linting

### ISSUE THREAD

**Issue by jack-fs** [gradientinstitute/causal-inspection#43]
Linting in CI has broken one too many times. Maybe we should replace flake8
- [x] Look into flake8 problem
- [x] Investigate alternatives
- [ ] Determine configuration
- [ ] Update code if need be (hopefully minor)
- [ ] Update GitHub actions

**Comment by jack-fs** [comment]
Useful (though outdated?) overview:
<https://pawamoy.github.io/posts/python-static-code-analysis-tools/>

| Tool                                                                                                                                                             | Notes                                                                                                                                                      | Pros                                       | Cons                                                                              |
|------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------|-----------------------------------------------------------------------------------|
| [prospector](https://prospector.landscape.io/en/master/index.html)                                                                                               | wraps PyFlakes, pycodestyle, McCabe, plus lots of extensions                                                                                               | Aggregator: a superset of flake8 in spirit | No extension ecosystem (is this a con?)                                           |
|                                                                                                                                                                  | Similar in idea to flake8: wraps pycodestyle, McCabe, but uses **PyLint** rather than PyFlakes by default                                                  | Explicitly aims to be less noisy/confusing |                                                                                   |
|                                                                                                                                                                  | Has additional features, broader scope compared to flake8 but no extension ecosystem                                                                       |                                            |                                                                                   |
| [pylama](https://github.com/klen/pylama)                                                                                                                         | Wraps pylint, mypy and others                                                                                                                              | Extensible                                 | Seems strictly less compelling than prospector,                                   |
|                                                                                                                                                                  |                                                                                                                                                            |                                            | based on activity and feature set                                                 |
| [Ruff](https://github.com/charliermarsh/ruff#faq)                                                                                                                | Implemented in rust                                                                                                                                        | Extremely fast                             | New                                                                               |
|                                                                                                                                                                  | [Intended to work alongside autoformatters](https://notes.crmarsh.com/python-tooling-could-be-much-much-faster), so stylistic lint rules are de-emphasised | intended as flake8 replacement             | Under very active development                                                     |
|                                                                                                                                                                  |                                                                                                                                                            | reimplements flake8 features               | Only a subset of flake8 lint rules                                                |
|                                                                                                                                                                  |                                                                                                                                                            |                                            | [Editor/LSP integration is WIP](https://github.com/charliermarsh/ruff/issues/271) |
| Related tools                                                                                                                                                    |                                                                                                                                                            |                                            |                                                                                   |
| [PyLint](https://github.com/PyCQA/pylint)                                                                                                                        | More complex checks/suggestions than flake8                                                                                                                |                                            | Slower than flake8                                                                |
| [pycodestyle](https://pycodestyle.pycqa.org/en/latest/)                                                                                                          | pep8 checker                                                                                                                                               |                                            |                                                                                   |
| [mypy](https://github.com/python/mypy)*[pyright](https://github.com/microsoft/pyright)*[pyre](https://pyre-check.org)/[pytype](https://github.com/google/pytype) | static type checkers                                                                                                                                       |                                            |                                                                                   |
| [bandit](https://github.com/PyCQA/bandit)                                                                                                                        | security-focussed; not particularly applicable for our project                                                                                             |                                            |                                                                                   |

</div>

**Comment by jack-fs** [comment]
https://github.com/tholo/pytest-flake8/issues/87 and its discussion seems to be relevant, given the errors being thrown in CI

**Comment by dsteinberg** [comment]
This is failing again - this time with a different problem.....

**Comment by jack-fs** [comment]
Seems to be due to flake8-quotes. See https://github.com/zheller/flake8-quotes/issues/115
