### ISSUE TITLE
bootstrapping over model selection and nested cross-validation

### ISSUE THREAD

**Issue by finnhacks42** [gradientinstitute/causal-inspection#6]
Set up evaluators to also work when we need two levels of bootstrapping/validation.

**Comment by dsteinberg** [comment]
I think the best way to solve this is with a custom scikit learn `_BaseKFold` splitter

**Comment by dsteinberg** [comment]
I think how this is currently implemented is fine - not need for extra complexity

**Comment by dsteinberg** [comment]
Actually - looking into this further - this is not doing what we want. Re-opening.
